### ISSUE TITLE
[BUG] Option `from-git` not working

### ISSUE THREAD

**Issue by j-m** [npm/libnpmversion#15]
# Summary

I can't get `from-git` to actually list any versions from git tags.

### Steps to Reproduce

* Create a folder & `npm init` and `git init` it
* Run `npm i libnpmversion` 
* Create `index.js` with the following
```js
const npmVersion = require('libnpmversion')
npmVersion('from-git').then(newVersion => {
  console.error('version updated!', newVersion)
})
```
* Stage all changes
* Commit 
* Tag as 0.1.0
* Run `node index.js`

### Actual behaviour

See
<pre
  C:\Users\*redacted*\Desktop\temp repo\node_modules\@npmcli\promise-spawn\index.js:64
          rej(Object.assign(new Error('command failed'), result))
                            ^

  Error: command failed
      at ChildProcess.<anonymous> (C:\Users\*redacted*\Desktop\temp repo\node_modules\@npmcli\promise-spawn\index.js:64:27)
      at ChildProcess.emit (node:events:365:28)
      at maybeClose (node:internal/child_process:1067:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
    cmd: 'C:\\Program Files\\Git\\cmd\\git.EXE',
    args: [
      '--no-replace-objects',
      'describe',
      '--tags',
      '--abbrev=0',
      "--match='*.*.*'"
    ],
    code: 128,
    signal: null,
    stdout: '',
    stderr: 'fatal: No names found, cannot describe anything.\n'
  }
</pre>

### Expected behaviour

See 0.1.0, or at least not to error 

<hr/>

This is the output when the command in the error is run:
<pre>
PS C:\Users\*redacted*\Desktop\temp repo> & 'C:\\Program Files\\Git\\cmd\\git.EXE' --no-replace-objects describe --tags --abbrev=0 --match='*.*.*'
0.1.0
</pre>

## References
  * Related to https://github.com/npm/cli/issues/3238

**Comment by wraithgar** [comment]
Looks like some versions of git didn't like the quotes around the `--match` param.  [This PR](https://github.com/npm/libnpmversion/pull/16) should fix it. Feel free to test it yourself locally.

**Comment by j-m** [comment]
Can confirm that the PR fixes the issue, thank you!

Tested using
`npm install npm/libnpmversion#pull/16/head`
